// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "messages.pb.h"
// @@protoc_insertion_point(includes)

namespace Communication {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class Message;

enum MessageTarget {
  Robot = 0,
  Unity = 1,
  Vision = 2
};
bool MessageTarget_IsValid(int value);
const MessageTarget MessageTarget_MIN = Robot;
const MessageTarget MessageTarget_MAX = Vision;
const int MessageTarget_ARRAYSIZE = MessageTarget_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageTarget_descriptor();
inline const ::std::string& MessageTarget_Name(MessageTarget value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageTarget_descriptor(), value);
}
inline bool MessageTarget_Parse(
    const ::std::string& name, MessageTarget* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageTarget>(
    MessageTarget_descriptor(), name, value);
}
enum MessageType {
  IdentificationRequest = 0,
  VelocityChange = 1,
  RotationChange = 2,
  StopMoving = 3,
  Indicate = 4,
  Identification = 5,
  LogError = 6,
  CustomEvent = 7,
  ShapeUpdate = 8
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = IdentificationRequest;
const MessageType MessageType_MAX = ShapeUpdate;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Communication.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 3;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 3;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required .Communication.MessageTarget messageTarget = 1;
  bool has_messagetarget() const;
  void clear_messagetarget();
  static const int kMessageTargetFieldNumber = 1;
  ::Communication::MessageTarget messagetarget() const;
  void set_messagetarget(::Communication::MessageTarget value);

  // required .Communication.MessageType messageType = 2;
  bool has_messagetype() const;
  void clear_messagetype();
  static const int kMessageTypeFieldNumber = 2;
  ::Communication::MessageType messagetype() const;
  void set_messagetype(::Communication::MessageType value);

  // optional .Communication.Messages.SetVelocity robotVelocity = 5;
  bool has_robotvelocity() const;
  void clear_robotvelocity();
  static const int kRobotVelocityFieldNumber = 5;
  const ::Communication::Messages::SetVelocity& robotvelocity() const;
  ::Communication::Messages::SetVelocity* mutable_robotvelocity();
  ::Communication::Messages::SetVelocity* release_robotvelocity();
  void set_allocated_robotvelocity(::Communication::Messages::SetVelocity* robotvelocity);

  // optional .Communication.Messages.SetRotation robotRotation = 6;
  bool has_robotrotation() const;
  void clear_robotrotation();
  static const int kRobotRotationFieldNumber = 6;
  const ::Communication::Messages::SetRotation& robotrotation() const;
  ::Communication::Messages::SetRotation* mutable_robotrotation();
  ::Communication::Messages::SetRotation* release_robotrotation();
  void set_allocated_robotrotation(::Communication::Messages::SetRotation* robotrotation);

  // optional .Communication.Messages.IdentificationResponse identificationResponse = 7;
  bool has_identificationresponse() const;
  void clear_identificationresponse();
  static const int kIdentificationResponseFieldNumber = 7;
  const ::Communication::Messages::IdentificationResponse& identificationresponse() const;
  ::Communication::Messages::IdentificationResponse* mutable_identificationresponse();
  ::Communication::Messages::IdentificationResponse* release_identificationresponse();
  void set_allocated_identificationresponse(::Communication::Messages::IdentificationResponse* identificationresponse);

  // optional .Communication.Messages.Error error = 8;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 8;
  const ::Communication::Messages::Error& error() const;
  ::Communication::Messages::Error* mutable_error();
  ::Communication::Messages::Error* release_error();
  void set_allocated_error(::Communication::Messages::Error* error);

  // optional .Communication.Messages.CustomMessage customMessage = 9;
  bool has_custommessage() const;
  void clear_custommessage();
  static const int kCustomMessageFieldNumber = 9;
  const ::Communication::Messages::CustomMessage& custommessage() const;
  ::Communication::Messages::CustomMessage* mutable_custommessage();
  ::Communication::Messages::CustomMessage* release_custommessage();
  void set_allocated_custommessage(::Communication::Messages::CustomMessage* custommessage);

  // optional .Communication.Messages.ShapeUpdateInfo shapeUpdate = 10;
  bool has_shapeupdate() const;
  void clear_shapeupdate();
  static const int kShapeUpdateFieldNumber = 10;
  const ::Communication::Messages::ShapeUpdateInfo& shapeupdate() const;
  ::Communication::Messages::ShapeUpdateInfo* mutable_shapeupdate();
  ::Communication::Messages::ShapeUpdateInfo* release_shapeupdate();
  void set_allocated_shapeupdate(::Communication::Messages::ShapeUpdateInfo* shapeupdate);

  // optional string stringData = 11;
  bool has_stringdata() const;
  void clear_stringdata();
  static const int kStringDataFieldNumber = 11;
  const ::std::string& stringdata() const;
  void set_stringdata(const ::std::string& value);
  void set_stringdata(const char* value);
  void set_stringdata(const char* value, size_t size);
  ::std::string* mutable_stringdata();
  ::std::string* release_stringdata();
  void set_allocated_stringdata(::std::string* stringdata);

  // @@protoc_insertion_point(class_scope:Communication.Message)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_messagetarget();
  inline void clear_has_messagetarget();
  inline void set_has_messagetype();
  inline void clear_has_messagetype();
  inline void set_has_robotvelocity();
  inline void clear_has_robotvelocity();
  inline void set_has_robotrotation();
  inline void clear_has_robotrotation();
  inline void set_has_identificationresponse();
  inline void clear_has_identificationresponse();
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_custommessage();
  inline void clear_has_custommessage();
  inline void set_has_shapeupdate();
  inline void clear_has_shapeupdate();
  inline void set_has_stringdata();
  inline void clear_has_stringdata();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  int messagetarget_;
  ::Communication::Messages::SetVelocity* robotvelocity_;
  ::Communication::Messages::SetRotation* robotrotation_;
  ::Communication::Messages::IdentificationResponse* identificationresponse_;
  ::Communication::Messages::Error* error_;
  ::Communication::Messages::CustomMessage* custommessage_;
  ::Communication::Messages::ShapeUpdateInfo* shapeupdate_;
  ::google::protobuf::internal::ArenaStringPtr stringdata_;
  int messagetype_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// required int32 id = 3;
inline bool Message::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Message::id() const {
  // @@protoc_insertion_point(field_get:Communication.Message.id)
  return id_;
}
inline void Message::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Communication.Message.id)
}

// required .Communication.MessageTarget messageTarget = 1;
inline bool Message::has_messagetarget() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_messagetarget() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_messagetarget() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_messagetarget() {
  messagetarget_ = 0;
  clear_has_messagetarget();
}
inline ::Communication::MessageTarget Message::messagetarget() const {
  // @@protoc_insertion_point(field_get:Communication.Message.messageTarget)
  return static_cast< ::Communication::MessageTarget >(messagetarget_);
}
inline void Message::set_messagetarget(::Communication::MessageTarget value) {
  assert(::Communication::MessageTarget_IsValid(value));
  set_has_messagetarget();
  messagetarget_ = value;
  // @@protoc_insertion_point(field_set:Communication.Message.messageTarget)
}

// required .Communication.MessageType messageType = 2;
inline bool Message::has_messagetype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_messagetype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_messagetype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_messagetype() {
  messagetype_ = 0;
  clear_has_messagetype();
}
inline ::Communication::MessageType Message::messagetype() const {
  // @@protoc_insertion_point(field_get:Communication.Message.messageType)
  return static_cast< ::Communication::MessageType >(messagetype_);
}
inline void Message::set_messagetype(::Communication::MessageType value) {
  assert(::Communication::MessageType_IsValid(value));
  set_has_messagetype();
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:Communication.Message.messageType)
}

// optional .Communication.Messages.SetVelocity robotVelocity = 5;
inline bool Message::has_robotvelocity() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_robotvelocity() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_robotvelocity() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_robotvelocity() {
  if (robotvelocity_ != NULL) robotvelocity_->::Communication::Messages::SetVelocity::Clear();
  clear_has_robotvelocity();
}
inline const ::Communication::Messages::SetVelocity& Message::robotvelocity() const {
  // @@protoc_insertion_point(field_get:Communication.Message.robotVelocity)
  return robotvelocity_ != NULL ? *robotvelocity_ : *default_instance_->robotvelocity_;
}
inline ::Communication::Messages::SetVelocity* Message::mutable_robotvelocity() {
  set_has_robotvelocity();
  if (robotvelocity_ == NULL) {
    robotvelocity_ = new ::Communication::Messages::SetVelocity;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.robotVelocity)
  return robotvelocity_;
}
inline ::Communication::Messages::SetVelocity* Message::release_robotvelocity() {
  // @@protoc_insertion_point(field_release:Communication.Message.robotVelocity)
  clear_has_robotvelocity();
  ::Communication::Messages::SetVelocity* temp = robotvelocity_;
  robotvelocity_ = NULL;
  return temp;
}
inline void Message::set_allocated_robotvelocity(::Communication::Messages::SetVelocity* robotvelocity) {
  delete robotvelocity_;
  robotvelocity_ = robotvelocity;
  if (robotvelocity) {
    set_has_robotvelocity();
  } else {
    clear_has_robotvelocity();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.robotVelocity)
}

// optional .Communication.Messages.SetRotation robotRotation = 6;
inline bool Message::has_robotrotation() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_robotrotation() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_robotrotation() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_robotrotation() {
  if (robotrotation_ != NULL) robotrotation_->::Communication::Messages::SetRotation::Clear();
  clear_has_robotrotation();
}
inline const ::Communication::Messages::SetRotation& Message::robotrotation() const {
  // @@protoc_insertion_point(field_get:Communication.Message.robotRotation)
  return robotrotation_ != NULL ? *robotrotation_ : *default_instance_->robotrotation_;
}
inline ::Communication::Messages::SetRotation* Message::mutable_robotrotation() {
  set_has_robotrotation();
  if (robotrotation_ == NULL) {
    robotrotation_ = new ::Communication::Messages::SetRotation;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.robotRotation)
  return robotrotation_;
}
inline ::Communication::Messages::SetRotation* Message::release_robotrotation() {
  // @@protoc_insertion_point(field_release:Communication.Message.robotRotation)
  clear_has_robotrotation();
  ::Communication::Messages::SetRotation* temp = robotrotation_;
  robotrotation_ = NULL;
  return temp;
}
inline void Message::set_allocated_robotrotation(::Communication::Messages::SetRotation* robotrotation) {
  delete robotrotation_;
  robotrotation_ = robotrotation;
  if (robotrotation) {
    set_has_robotrotation();
  } else {
    clear_has_robotrotation();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.robotRotation)
}

// optional .Communication.Messages.IdentificationResponse identificationResponse = 7;
inline bool Message::has_identificationresponse() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_identificationresponse() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_identificationresponse() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_identificationresponse() {
  if (identificationresponse_ != NULL) identificationresponse_->::Communication::Messages::IdentificationResponse::Clear();
  clear_has_identificationresponse();
}
inline const ::Communication::Messages::IdentificationResponse& Message::identificationresponse() const {
  // @@protoc_insertion_point(field_get:Communication.Message.identificationResponse)
  return identificationresponse_ != NULL ? *identificationresponse_ : *default_instance_->identificationresponse_;
}
inline ::Communication::Messages::IdentificationResponse* Message::mutable_identificationresponse() {
  set_has_identificationresponse();
  if (identificationresponse_ == NULL) {
    identificationresponse_ = new ::Communication::Messages::IdentificationResponse;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.identificationResponse)
  return identificationresponse_;
}
inline ::Communication::Messages::IdentificationResponse* Message::release_identificationresponse() {
  // @@protoc_insertion_point(field_release:Communication.Message.identificationResponse)
  clear_has_identificationresponse();
  ::Communication::Messages::IdentificationResponse* temp = identificationresponse_;
  identificationresponse_ = NULL;
  return temp;
}
inline void Message::set_allocated_identificationresponse(::Communication::Messages::IdentificationResponse* identificationresponse) {
  delete identificationresponse_;
  identificationresponse_ = identificationresponse;
  if (identificationresponse) {
    set_has_identificationresponse();
  } else {
    clear_has_identificationresponse();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.identificationResponse)
}

// optional .Communication.Messages.Error error = 8;
inline bool Message::has_error() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Message::set_has_error() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Message::clear_has_error() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Message::clear_error() {
  if (error_ != NULL) error_->::Communication::Messages::Error::Clear();
  clear_has_error();
}
inline const ::Communication::Messages::Error& Message::error() const {
  // @@protoc_insertion_point(field_get:Communication.Message.error)
  return error_ != NULL ? *error_ : *default_instance_->error_;
}
inline ::Communication::Messages::Error* Message::mutable_error() {
  set_has_error();
  if (error_ == NULL) {
    error_ = new ::Communication::Messages::Error;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.error)
  return error_;
}
inline ::Communication::Messages::Error* Message::release_error() {
  // @@protoc_insertion_point(field_release:Communication.Message.error)
  clear_has_error();
  ::Communication::Messages::Error* temp = error_;
  error_ = NULL;
  return temp;
}
inline void Message::set_allocated_error(::Communication::Messages::Error* error) {
  delete error_;
  error_ = error;
  if (error) {
    set_has_error();
  } else {
    clear_has_error();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.error)
}

// optional .Communication.Messages.CustomMessage customMessage = 9;
inline bool Message::has_custommessage() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Message::set_has_custommessage() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Message::clear_has_custommessage() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Message::clear_custommessage() {
  if (custommessage_ != NULL) custommessage_->::Communication::Messages::CustomMessage::Clear();
  clear_has_custommessage();
}
inline const ::Communication::Messages::CustomMessage& Message::custommessage() const {
  // @@protoc_insertion_point(field_get:Communication.Message.customMessage)
  return custommessage_ != NULL ? *custommessage_ : *default_instance_->custommessage_;
}
inline ::Communication::Messages::CustomMessage* Message::mutable_custommessage() {
  set_has_custommessage();
  if (custommessage_ == NULL) {
    custommessage_ = new ::Communication::Messages::CustomMessage;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.customMessage)
  return custommessage_;
}
inline ::Communication::Messages::CustomMessage* Message::release_custommessage() {
  // @@protoc_insertion_point(field_release:Communication.Message.customMessage)
  clear_has_custommessage();
  ::Communication::Messages::CustomMessage* temp = custommessage_;
  custommessage_ = NULL;
  return temp;
}
inline void Message::set_allocated_custommessage(::Communication::Messages::CustomMessage* custommessage) {
  delete custommessage_;
  custommessage_ = custommessage;
  if (custommessage) {
    set_has_custommessage();
  } else {
    clear_has_custommessage();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.customMessage)
}

// optional .Communication.Messages.ShapeUpdateInfo shapeUpdate = 10;
inline bool Message::has_shapeupdate() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Message::set_has_shapeupdate() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Message::clear_has_shapeupdate() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Message::clear_shapeupdate() {
  if (shapeupdate_ != NULL) shapeupdate_->::Communication::Messages::ShapeUpdateInfo::Clear();
  clear_has_shapeupdate();
}
inline const ::Communication::Messages::ShapeUpdateInfo& Message::shapeupdate() const {
  // @@protoc_insertion_point(field_get:Communication.Message.shapeUpdate)
  return shapeupdate_ != NULL ? *shapeupdate_ : *default_instance_->shapeupdate_;
}
inline ::Communication::Messages::ShapeUpdateInfo* Message::mutable_shapeupdate() {
  set_has_shapeupdate();
  if (shapeupdate_ == NULL) {
    shapeupdate_ = new ::Communication::Messages::ShapeUpdateInfo;
  }
  // @@protoc_insertion_point(field_mutable:Communication.Message.shapeUpdate)
  return shapeupdate_;
}
inline ::Communication::Messages::ShapeUpdateInfo* Message::release_shapeupdate() {
  // @@protoc_insertion_point(field_release:Communication.Message.shapeUpdate)
  clear_has_shapeupdate();
  ::Communication::Messages::ShapeUpdateInfo* temp = shapeupdate_;
  shapeupdate_ = NULL;
  return temp;
}
inline void Message::set_allocated_shapeupdate(::Communication::Messages::ShapeUpdateInfo* shapeupdate) {
  delete shapeupdate_;
  shapeupdate_ = shapeupdate;
  if (shapeupdate) {
    set_has_shapeupdate();
  } else {
    clear_has_shapeupdate();
  }
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.shapeUpdate)
}

// optional string stringData = 11;
inline bool Message::has_stringdata() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Message::set_has_stringdata() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Message::clear_has_stringdata() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Message::clear_stringdata() {
  stringdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_stringdata();
}
inline const ::std::string& Message::stringdata() const {
  // @@protoc_insertion_point(field_get:Communication.Message.stringData)
  return stringdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_stringdata(const ::std::string& value) {
  set_has_stringdata();
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Communication.Message.stringData)
}
inline void Message::set_stringdata(const char* value) {
  set_has_stringdata();
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Communication.Message.stringData)
}
inline void Message::set_stringdata(const char* value, size_t size) {
  set_has_stringdata();
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Communication.Message.stringData)
}
inline ::std::string* Message::mutable_stringdata() {
  set_has_stringdata();
  // @@protoc_insertion_point(field_mutable:Communication.Message.stringData)
  return stringdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_stringdata() {
  // @@protoc_insertion_point(field_release:Communication.Message.stringData)
  clear_has_stringdata();
  return stringdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_stringdata(::std::string* stringdata) {
  if (stringdata != NULL) {
    set_has_stringdata();
  } else {
    clear_has_stringdata();
  }
  stringdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stringdata);
  // @@protoc_insertion_point(field_set_allocated:Communication.Message.stringData)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Communication

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Communication::MessageTarget> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Communication::MessageTarget>() {
  return ::Communication::MessageTarget_descriptor();
}
template <> struct is_proto_enum< ::Communication::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Communication::MessageType>() {
  return ::Communication::MessageType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
